### ISSUE TITLE
Can we remove "News" in favor of using "Blog" instead

### ISSUE THREAD

**Issue by mikeputnam** [dhmncivichacks/timewebsite#37]
@bobwaldron 

Are news and blog items sufficiently different to warrant multiple destinations? Does having both dilute users attention?

If I'm wrong feel free to disagree with me and close this issue, perhaps providing details.

**Comment by bobwaldron** [comment]
At this stage of site build, OK to remove News if that helps you. News and
Blog are 2 different things, but can leave News for version down the road.
On May 30, 2016 3:25 PM, "Mike Putnam" <notifications@github.com> wrote:

Assigned #37 <https://github.com/dhmncivichacks/timewebsite/issues/37> to
@bobwaldron <https://github.com/bobwaldron>.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/dhmncivichacks/timewebsite/issues/37#event-676295759>,
or mute the thread
<https://github.com/notifications/unsubscribe/AJBl3d8eDpe43Bwmy77a2kqpUXSOiEBaks5qGznCgaJpZM4Ip_ih>
.

**Comment by bobwaldron** [comment]
I wasn't optimizing design for the 80%, was just putting categories I'd
want to have.

Will look for examples of sites with both. In my vision, News would be
aggregated excerpts from other sites, a probably one or a couple news
feeds. Blog would be posts by me or any TIME community members who wanted
to blather about whatever.

**Comment by mikeputnam** [comment]
News and Blog are not the same. Closing this issue and proceeding with building both.
